### ISSUE TITLE
Heyu won't start 

### ISSUE THREAD

**Issue by Giorgiofox** [NorthernMan54/homebridge-heyu#11]
I've upgraded to 0.3.17 (using HomeBridge 0.4.36) and now Homebridge won't start:
I need to remove Heyu from platforms to make it start again:
this my conf:

         {
            "platform": "Heyu",
            "name": "Heyu",
            "heyuExec": "/usr/local/bin/heyu",
            "x10conf": "/etc/heyu/x10.conf",
            "useFireCracker": false,
            "cputemp": "cputemp"
        },

Heyu from command line works well.

**Comment by NorthernMan54** [comment]
Any chance you can share a log file showing why homebridge won’t start? Usually it is pretty verbose when it can’t start shows exactly where the problem is.

PS I’m running 0.4.36 without a problem

**Comment by Giorgiofox** [comment]
Reading Log, I can't discover any issue:
after start Homebridge log freeze at this point:
[1/21/2018, 4:14:52 PM] ---
[1/21/2018, 4:14:52 PM] Loading 3 platforms...
[1/21/2018, 4:14:52 PM] [Config] Initializing config platform...
[1/21/2018, 4:14:52 PM] [Heyu] Initializing Heyu platform...
[1/21/2018, 4:14:52 PM] [Heyu] Heyu Platform Plugin Loaded

**Comment by NorthernMan54** [comment]
Hummm try with debugging enabled

DEBUG=* homebridge

**Comment by Giorgiofox** [comment]
Can you please explain me where I can enable debug?

**Comment by Giorgiofox** [comment]
found:
/usr/local/lib/node_modules/homebridge-heyu/index.js:96
    var line = match[0].split(/[ \t]+/);
                    ^
TypeError: Cannot read property '0' of null
    at readHousecode (/usr/local/lib/node_modules/homebridge-heyu/index.js:96:21)
    at HeyuPlatform (/usr/local/lib/node_modules/homebridge-heyu/index.js:56:22)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:425:7)
    at startup (bootstrap_node.js:146:9)
    at bootstrap_node.js:540:3

**Comment by NorthernMan54** [comment]
I think I need a better error for this.  It is complaining that you haven’t defined HOUSECODE in the x10.conf

This was added in the latest release.

**Comment by Giorgiofox** [comment]
Solved! in X10.con the HOUSECODE was commented.
Thank you!

**Comment by NorthernMan54** [comment]
Tks

I have updated the README to point out your problem, until I can put in a better fix.
